apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-java-springboot-basic-wzmt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-java-springboot-basic-wzmt
    app.kubernetes.io/part-of: load-app-70aa6507-0dd7-454b-a4fc-a1b5ae797556
  name: devfile-sample-java-springboot-basic-wzmt
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: java-springboot-app
    app.kubernetes.io/instance: devfile-sample-java-springboot-basic-wzmt
status:
  loadBalancer: {}
